In [2]:
import numpy as np
import pandas as pd

In [4]:
a = [[1,2],[3,4]]
arr = np.array(a)
arr

array([[1, 2],
       [3, 4]])

In [6]:
df = pd.DataFrame(a)
df

   0  1
0  1  2
1  3  4

In [19]:
data = pd.DataFrame([{"maths":12, "science":24, "name": "A"}, {"maths" : 24, "science": 21, "name" : "B"}]* 100)
data

     maths  science name
0       12       24    A
1       24       21    B
2       12       24    A
3       24       21    B
4       12       24    A
..     ...      ...  ...
195     24       21    B
196     12       24    A
197     24       21    B
198     12       24    A
199     24       21    B

[200 rows x 3 columns]

You can access a Series in pandas in the following ways:

In [20]:
data.maths

0      12
1      24
2      12
3      24
4      12
       ..
195    24
196    12
197    24
198    12
199    24
Name: maths, Length: 200, dtype: int64

In [21]:
data["maths"]

0      12
1      24
2      12
3      24
4      12
       ..
195    24
196    12
197    24
198    12
199    24
Name: maths, Length: 200, dtype: int64

In [22]:
data.get("maths")

0      12
1      24
2      12
3      24
4      12
       ..
195    24
196    12
197    24
198    12
199    24
Name: maths, Length: 200, dtype: int64

In [23]:
print(type(data["maths"]))

<class 'pandas.Series'>

In [24]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   maths    200 non-null    int64
 1   science  200 non-null    int64
 2   name     200 non-null    str
dtypes: int64(2), str(1)
memory usage: 4.8 KB

In [27]:
data.head()
data.head(1)

   maths  science name
0     12       24    A

In [29]:
data.tail()
data.tail(1)

     maths  science name
199     24       21    B

In [34]:
data.size

600

Starting the practice with some real world data.
Dataset name Covid-19

In [48]:
countries_data = pd.read_csv("../data/covid-19/countries-aggregated-sample.csv")
countries_data

             Date      Country  Confirmed  Recovered  Deaths
0      2020-01-22  Afghanistan          0          0       0
1      2020-01-23  Afghanistan          0          0       0
2      2020-01-24  Afghanistan          0          0       0
3      2020-01-25  Afghanistan          0          0       0
4      2020-01-26  Afghanistan          0          0       0
...           ...          ...        ...        ...     ...
76812  2020-05-09       Kosovo        862        622      28
76813  2020-05-10       Kosovo        870        653      28
76814  2020-05-11       Kosovo        884        655      28
76815  2020-05-12       Kosovo        895        657      28
76816  2020-05-13       Kosovo        919        671      29

[76817 rows x 5 columns]

In [49]:
countries_data.head()

         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0          0       0
1  2020-01-23  Afghanistan          0          0       0
2  2020-01-24  Afghanistan          0          0       0
3  2020-01-25  Afghanistan          0          0       0
4  2020-01-26  Afghanistan          0          0       0

In [50]:
countries_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 76817 entries, 0 to 76816
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       76817 non-null  str
 1   Country    76817 non-null  str
 2   Confirmed  76817 non-null  int64
 3   Recovered  76817 non-null  int64
 4   Deaths     76817 non-null  int64
dtypes: int64(3), str(2)
memory usage: 2.9 MB

In [51]:
countries_data["Date"] = pd.to_datetime(countries_data["Date"])

In [55]:
# to find the count of unique values in a Series inside a Data Frame
countries_data["Date"].nunique() # field names are case sensitive.

816

In [52]:
countries_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 76817 entries, 0 to 76816
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       76817 non-null  datetime64[us]
 1   Country    76817 non-null  str
 2   Confirmed  76817 non-null  int64
 3   Recovered  76817 non-null  int64
 4   Deaths     76817 non-null  int64
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 2.9 MB

In [57]:
# Indexing in pandas - column indexing and the indexes don't need to be unique
countries_data.loc[76814]

Date         2020-05-11 00:00:00
Country                   Kosovo
Confirmed                    884
Recovered                    655
Deaths                        28
Name: 76814, dtype: object

In [58]:
countries_data.iloc[76814]

Date         2020-05-11 00:00:00
Country                   Kosovo
Confirmed                    884
Recovered                    655
Deaths                        28
Name: 76814, dtype: object

In [71]:
print(countries_data.set_index("Country").iloc[76814])
print(countries_data.set_index("Country").loc["India"])

Date         2020-05-11 00:00:00
Confirmed                    884
Recovered                    655
Deaths                        28
Name: Kosovo, dtype: object
              Date  Confirmed  Recovered  Deaths
Country
India   2020-01-22          0          0       0
India   2020-01-23          0          0       0
India   2020-01-24          0          0       0
India   2020-01-25          0          0       0
India   2020-01-26          0          0       0
...            ...        ...        ...     ...
India   2022-04-12   43038016          0  521736
India   2022-04-13   43039023          0  521737
India   2022-04-14   43039972          0  521743
India   2022-04-15   43040947          0  521747
India   2022-04-16   43042097          0  521751

[816 rows x 4 columns]

In [78]:
print(countries_data["Country"].unique())
print("-" * 50)
print("Number of unique countries", countries_data["Country"].nunique())

<StringArray>
[             'Afghanistan',                  'Albania',
                  'Algeria',                  'Andorra',
                   'Angola',               'Antarctica',
      'Antigua and Barbuda',                'Argentina',
                  'Armenia',                'Australia',
                  'Austria',               'Azerbaijan',
                  'Bahamas',                  'Bahrain',
               'Bangladesh',                 'Barbados',
                  'Belarus',                  'Belgium',
                   'Belize',                    'Benin',
                   'Bhutan',                  'Bolivia',
   'Bosnia and Herzegovina',                 'Botswana',
                   'Brazil',                   'Brunei',
                 'Bulgaria',             'Burkina Faso',
                    'Burma',                  'Burundi',
               'Cabo Verde',                 'Cambodia',
                 'Cameroon',                   'Canada',
 'Central African Republic',                     'Chad',
                    'Chile',                    'China',
                 'Colombia',                  'Comoros',
      'Congo (Brazzaville)',         'Congo (Kinshasa)',
               'Costa Rica',            'Cote d'Ivoire',
                  'Croatia',                     'Cuba',
                   'Cyprus',                  'Czechia',
                  'Denmark',         'Diamond Princess',
                 'Djibouti',                 'Dominica',
       'Dominican Republic',                  'Ecuador',
                    'Egypt',              'El Salvador',
        'Equatorial Guinea',                  'Eritrea',
                  'Estonia',                 'Eswatini',
                 'Ethiopia',                     'Fiji',
                  'Finland',                   'France',
                    'Gabon',                   'Gambia',
                  'Georgia',                  'Germany',
                    'Ghana',                   'Greece',
                  'Grenada',                'Guatemala',
                   'Guinea',            'Guinea-Bissau',
                   'Guyana',                    'Haiti',
                 'Holy See',                 'Honduras',
                  'Hungary',                  'Iceland',
                    'India',                'Indonesia',
                     'Iran',                     'Iraq',
                  'Ireland',                   'Israel',
                    'Italy',                  'Jamaica',
                    'Japan',                   'Jordan',
               'Kazakhstan',                    'Kenya',
                 'Kiribati',             'Korea, South',
                   'Kosovo']
Length: 95, dtype: str
--------------------------------------------------
Number of unique countries 95